// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Creator struct {
	Address     string `json:"address"`
	AmountToken int    `json:"amount_token"`
}

type Todo struct {
	ID      string   `json:"id"`
	Text    string   `json:"text"`
	Done    bool     `json:"done"`
	Creator *Creator `json:"creator"`
}
